### ISSUE TITLE
add a datepicker for the date field on the book page

### ISSUE THREAD

**Issue by bbelderbos** [PyBites-Open-Source/pbreadinglist#21]
<img width="637" alt="Screenshot 2020-10-10 at 12 15 27" src="https://user-images.githubusercontent.com/387927/95652588-84203a00-0af2-11eb-9b47-dd9244a0fba3.png">

**Comment by greywidget** [comment]
It looks like this functionality has already been added?

![image](https://user-images.githubusercontent.com/45608909/95919850-37fd2000-0da6-11eb-8be2-c975fb6d2bcb.png)

**Comment by bbelderbos** [comment]
Good catch @greywidget, this is a Mac Safari browser issue, it works on Chrome. So maybe a JS fix would be nice for this: https://stackoverflow.com/questions/35682138/html5-date-picker-doesnt-show-on-safari

**Comment by pybites** [comment]
Fixed: https://github.com/PyBites-Open-Source/pbreadinglist/pull/24
