### ISSUE TITLE
prevent account creation for email that is already in the db

### ISSUE THREAD

**Issue by bbelderbos** [PyBites-Open-Source/pbreadinglist#22]
I am even surprised that `django-registration` lets this through?

```
> select count(*) from auth_user where email = 'bobbelderbos@gmail.com'
+---------+
| count   |
|---------|
| 2       |
+---------+
```

A user trying to register with an email that is already in the db should be prevented from doing so in the registration form.

**Comment by Ankit-rana** [comment]
I have found link to make email unique in django
https://stackoverflow.com/questions/53461410/make-user-email-unique-django/53461823
If this is okay, I can create a patch.
Thanks

**Comment by bbelderbos** [comment]
Thanks @Ankit-rana how do you plan to fix it? I believe using `AbstractUser` is only recommended when you start your project (prior to running any migration). Also this is registration plugin code, so ideally we fix it there, I found this: https://stackoverflow.com/a/19383392

**Comment by bbelderbos** [comment]
resolved by https://github.com/PyBites-Open-Source/pbreadinglist/pull/36
