### ISSUE TITLE
add a setup.py file so we can deploy the package to PyPI

### ISSUE THREAD

**Issue by bbelderbos** [PyBites-Open-Source/pbreadinglist#23]

**Comment by harshiniwho** [comment]
Hi! If this issue is still open, I can work on it!

**Comment by bbelderbos** [comment]
Thanks @harshiniwho that would be awesome.

**Comment by chillerm** [comment]
Would you like to dockerize it instead?   Seems like this is more of an app than a library?

**Comment by bbelderbos** [comment]
Sure that would be cool, thanks

**Comment by chillerm** [comment]
Hey @bbelderbos Let me know if that submission works.  I can add details to publish to docker hub if you'd like, just let me know!

**Comment by bbelderbos** [comment]
@chillerm really cool, thanks.
