### ISSUE TITLE
Upgrade to the latest Django version

### ISSUE THREAD

**Issue by pybites** [PyBites-Open-Source/pbreadinglist#7]
Which will break `django-registration` so either upgrade that to the latest or swap it out for `django-allauth`.

**Comment by GorettiRivera** [comment]
@pybites Could you please assign this to me?

**Comment by bbelderbos** [comment]
Sure, thanks @GorettiRivera 
Let me know what you do with the registration plugin ...

**Comment by GorettiRivera** [comment]
@bbelderbos 
Sure, are you planning to upgrade Django to 3.1 or lower? Because we can upgrade both to 3.1.

Django==3.1
django-registration==3.1

**Comment by bbelderbos** [comment]
The later/ more recent the better. Btw I am fixing some setup issues, I will link a PR here in a bit.

**Comment by bbelderbos** [comment]
I ran into these issues: https://github.com/PyBites-Open-Source/pbreadinglist/pull/12
If you pull `develop` you should have a more smoother setup process :)

**Comment by bbelderbos** [comment]
And 2 more fixes FYI:
https://github.com/PyBites-Open-Source/pbreadinglist/pull/13 
https://github.com/PyBites-Open-Source/pbreadinglist/pull/14
